FROM ubuntu:22.04

#installation of wget and missing commands
RUN apt-get update --fix-missing \
&& apt-get install -y wget \
&& cd /usr/local/

#Installation of dependancies
RUN apt-get install -y tar wget make gcc libz-dev build-essential autoconf automake gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev

#compilation
RUN wget https://github.com/alexdobin/STAR/archive/2.7.10a.tar.gz \
&& tar -xzf 2.7.10a.tar.gz \
&& cd STAR-2.7.10a/source \
&& make STAR
